### Start producer-1
POST {{endpoint}}/api/worker/producer/producer-1/topic1?interval=500
Content-Type: application/json

### Start consumer-1
POST {{endpoint}}/api/worker/consumer/consumer-1/topic1?interval=0&groupId=consumers-1&shouldFail=false
Content-Type: application/json

### Get topic leaders
GET {{endpoint}}/api/worker/consumer/leader
Content-Type: application/json

### Start consumer-2
POST {{endpoint}}/api/worker/consumer/consumer-2/topic1?interval=0&groupId=consumers-1&shouldFail=false
Content-Type: application/json

### Get topic leaders
GET {{endpoint}}/api/worker/consumer/leader
Content-Type: application/json

### Start consumer-3
POST {{endpoint}}/api/worker/consumer/consumer-3/topic1?interval=0&groupId=consumers-1&shouldFail=false
Content-Type: application/json

### Get topic leaders
GET {{endpoint}}/api/worker/consumer/leader
Content-Type: application/json

### Update consumer-1 with slow consume
PUT {{endpoint}}/api/worker/consumer/consumer-1/topic1?groupId=consumers-1&interval=10000
Content-Type: application/json

### Update consumer-2 with not commit
PUT {{endpoint}}/api/worker/consumer/consumer-2/topic1?groupId=consumers-2&shouldFail=true
Content-Type: application/json

### Update consumer-1 normal consume
PUT {{endpoint}}/api/worker/consumer/consumer-1/topic1?groupId=consumers-1&interval=0
Content-Type: application/json

### Get events
GET {{endpoint}}/api/event
Content-Type: application/json

### Get events
GET {{endpoint}}/api/event?includeOpen=false&includeClose=true
Content-Type: application/json
