version: '3.4'

services:
  burrow1:
    image: burrow_burrow
    container_name: burrow1
    volumes:
      - ${PWD}/burrow/burrow1/config:/etc/burrow/
    ports:
      - 8000:8000
    depends_on:
      - zoo1
      - kafka1
      - kafka2
      - kafka3
    restart: always
  burrow2:
    image: burrow_burrow
    container_name: burrow2
    volumes:
      - ${PWD}/burrow/burrow2/config:/etc/burrow/
    ports:
      - 8100:8000
    depends_on:
      - zoo1
      - kafka1
      - kafka2
      - kafka3
    restart: always
  burrow-ui:
    image: generalmills/burrowui
    container_name: burrow-ui
    ports:
      - 3100:3000
    environment:
      BURROW_HOME: "http://burrow1:8000/v3/kafka"
    depends_on:
      - burrow1
    restart: always
  burrow-dashboard:
    image: joway/burrow-dashboard:latest
    container_name: burrow-dashboard
    ports:
      - 3000:80
    environment:
      BURROW_BACKEND: "http://burrow1:8000"
    depends_on:
      - burrow1
    restart: always