[zookeeper]
servers = ["zoo1:2181"]
timeout = 6
root-path = "/burrow"

[client-profile.test]
client-id = "burrow-test"
kafka-version = "2.1.0"

[cluster.local]
class-name = "kafka"
servers = ["kafka1:19092", "kafka1:19093", "kafka1:19094"]
client-profile = "test"
topic-refresh = 5
offset-refresh = 35
groups-reaper-refresh = 0

[consumer.local]
class-name = "kafka"
cluster = "local"
servers = ["kafka1:19092", "kafka1:19093", "kafka1:19094"]
client-profile = "test"
group-denylist = "^(console-consumer-|python-kafka-consumer-).*$"
group-allowlist = ""

[httpserver.default]
address = ":8000"

[storage.default]
class-name = "inmemory"
workers = 20
intervals = 5
expire-group = 604800
min-distance = 1

[notifier.default]
class-name="http"
url-open="http://demo-app:8080/api/event"
url-close="http://demo-app:8080/api/event"
# report interval
interval=5
timeout=5
keepalive=30
extras={ api_key="REDACTED", app="burrow", tier="STG", fabric="mydc" }
template-open="/etc/burrow/http-post.tmpl"
template-close="/etc/burrow/http-delete.tmpl"
method-close="DELETE"
send-close=true
threshold=2